version: '3'

services:
  app:
    build:
      context: ./node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: sh -c "npm install && node index.js"
    tty: true
  db:
    build:
      context: ./mysql
    networks:
      - node-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    container_name: db
    # command: --innodb-use-native-aio=0
    tty: true
  nginx:
    build:
      context: ./nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
    - app
    container_name: nginx
  
networks:
  node-network:
    driver: bridge